import { Toaster } from 'react-hot-toast';
import Footer from "./components/footer/Footer";
import Navbar from './components/navbar/Navbar2';
import ClientSessionProvider from './context/ClientSessionProvider';
import "./globals.css";


export const metadata = {
  title: "RPL",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body
      >
        <Toaster
          position="top-right"
          reverseOrder={false} />
        <ClientSessionProvider>
          <Navbar />
          {children}
          <Footer />
        </ClientSessionProvider>
      </body>
    </html>
  );
}
